spring.application.name=finanlice

spring.datasource.url=jdbc:mysql://localhost/3306/finanlice
spring.datasource.username=root
spring.datasource.password=SUA_SENHA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true